import type {SeoBusiness,SeoReport} from './seo-growth.mjs';
export type SearchManifest={workspaceId:string;property:string;searchType:'web';dimensions:('query'|'page'|'date'|'country'|'device')[];startDate:string;endDate:string;observedAt?:string};
export type SearchEvidence={version:'growth-starter.search-evidence.v1';workspaceId:string;property:string;searchType:string;dimensions:string[];startDate:string;endDate:string;verification:'user_supplied_unverified';isComplete:false;rows:Array<Record<string,unknown>>};
export type SearchAnalysis={version:'growth-starter.search-analysis.v1';workspaceId:string;source:string;property:string;dimensions:string[];
 period:{start:string;end:string};
 summary:{clicks:number;impressions:number;ctr:number|null;averagePosition:number|null;rows:number};
 opportunities:Array<{kind:string;query:string;page:string|null;service:string;rationale:string;status:string;evidence:{source:string;property:string;range:string[];impressions:number;clicks:number;ctr:number|null;averagePosition:number}}>;
 keywords:Array<{phrase:string;searchEvidence:{status:string}}>;
 aeoProposals:Array<{question:string;answerDraft:string;status:string}>;
 comparison:null|{status:string;change:{clicks:number;impressions:number;ctrPercentagePoints:number|null;averagePosition:number|null};warning:string};
 existingSeoFindings:Array<{code:string;finding:string;url:string}>;
 proposedTasks:Array<{finding:string;recommendation:string;status:string}>;
 limitations:string[];verification:string;externalActions:{enabled:false;publishing:false;persistentWrites:false}};
export function importSearchConsoleExport(input:{content:string;format:'csv'|'json';manifest:SearchManifest;business:SeoBusiness}):SearchEvidence;
export function analyzeImportedSearchEvidence(report:SeoReport,evidence:SearchEvidence,opts?:{previous?:SearchEvidence|null}):SearchAnalysis;
export function compareSearchEvidence(earlier:SearchEvidence,later:SearchEvidence):unknown;
export function exportSearchAnalysisCsv(result:SearchAnalysis):string;
export function interpretSeoInstruction(input:{workspaceId:string;instruction:string;business:SeoBusiness;service:string;area:string;evidenceSources?:string[]}):{intent:string[];externalActionsEnabled:false;reviewStatus:string};
export const SEARCH_IMPORT_LIMITS:{bytes:number;rows:number;field:number;days:number};
export const SEARCH_PROVIDER_CONTRACTS:Record<string,{status:string;scope:string}>;
